source "https://rubygems.org"

# Jekyll et thème
gem "jekyll", "~> 4.3.2"
gem "minimal-mistakes-jekyll", "~> 4.24" # adapte la version à la doc du thème

# HTML Proofer pour les tests
gem "html-proofer", "~> 5.0"

# Plugins Jekyll officiels
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.16"
  gem "jekyll-sitemap", "~> 1.4"
end
