source "https://rubygems.org"

# Jekyll principal
gem "jekyll", "~> 4.3.2"

# Thème Minimal Mistakes compatible Jekyll 4
gem "minimal-mistakes-jekyll", "~> 4.24"

# HTML Proofer pour tester le site
gem "html-proofer", "~> 5.0"

# Plugins officiels Jekyll
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.16"
  gem "jekyll-sitemap", "~> 1.4"
end
